# Generated by Django 4.1.1 on 2022-12-05 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal',
            name='phone_number',
        ),
    ]
